name: flutter_crud_firebase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  formz: ^0.7.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.2.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  firebase_storage: ^12.1.1
  image_picker: ^1.0.4
  skeletonizer: ^1.4.1+1
  equatable: ^2.0.5
  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/bold.ttf
    - family: semibold
      fonts:
        - asset: assets/fonts/semibold.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/medium.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/regular.ttf
    - family: light
      fonts:
        - asset: assets/fonts/light.ttf
