name: authentication_repository
description: A repository for managing user authentication domain.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_auth: ^5.1.2
  shared_pref: 
    path: ../shared_pref
  equatable: ^2.0.5
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.1.0