// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovKxBOR_7irO8Nm7im5bCX4LVFhVpLWQ',
    appId: '1:403560543340:web:c2187f938eb48678e25449',
    messagingSenderId: '403560543340',
    projectId: 'flutter-crud-11564',
    authDomain: 'flutter-crud-11564.firebaseapp.com',
    storageBucket: 'flutter-crud-11564.appspot.com',
    measurementId: 'G-MEQ2P57H80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4m3TUKkBy8RgzMqnziOmcLF1oic6ahFQ',
    appId: '1:403560543340:android:f72ea1df1481e761e25449',
    messagingSenderId: '403560543340',
    projectId: 'flutter-crud-11564',
    storageBucket: 'flutter-crud-11564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjUJU0urxuNRoUDcyUgCUDeYWCkF3t98',
    appId: '1:403560543340:ios:c28fa22fa72c1c02e25449',
    messagingSenderId: '403560543340',
    projectId: 'flutter-crud-11564',
    storageBucket: 'flutter-crud-11564.appspot.com',
    androidClientId: '403560543340-r48210odcbo7fht2tgkroa07k007d69l.apps.googleusercontent.com',
    iosClientId: '403560543340-437g6i6v6mpb2vsrdi2fhhhkn8m0jamu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEjUJU0urxuNRoUDcyUgCUDeYWCkF3t98',
    appId: '1:403560543340:ios:c28fa22fa72c1c02e25449',
    messagingSenderId: '403560543340',
    projectId: 'flutter-crud-11564',
    storageBucket: 'flutter-crud-11564.appspot.com',
    androidClientId: '403560543340-r48210odcbo7fht2tgkroa07k007d69l.apps.googleusercontent.com',
    iosClientId: '403560543340-437g6i6v6mpb2vsrdi2fhhhkn8m0jamu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAovKxBOR_7irO8Nm7im5bCX4LVFhVpLWQ',
    appId: '1:403560543340:web:2d9aa735007e8181e25449',
    messagingSenderId: '403560543340',
    projectId: 'flutter-crud-11564',
    authDomain: 'flutter-crud-11564.firebaseapp.com',
    storageBucket: 'flutter-crud-11564.appspot.com',
    measurementId: 'G-0G7NZD2RR2',
  );

}